version: '3.8'
services:
  postgres:
    image: postgres:17-alpine
    container_name: polar_inmobiliaria_db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: polar_inmobiliaria
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: