name: Deploy to VPS

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            cd ~/project-inmobiliaria
            git reset --hard
            git pull origin dev
            rm -f package-lock.json
            yarn install --ignore-engines
            yarn add dotenv --ignore-engines
            npx prisma generate
            yarn build
            pm2 restart ecosystem.config.js --update-env
